name: Fetch Latest Lecture Data and Create Pull Request

on:
  # schedule:
  #   # JST 15:40 (UTC 6:40) every 3rd day of the month (best practice: https://zenn.dev/rie_amasato/articles/f901ef9fb19415)
  #   - cron: "40 6 1 */3 *"
  push:
    branches:
      - features/modify-Actions-to-create-PR
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  fetch_lecture_codes:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
          cache: "pip"
      - run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --upgrade get-chrome-driver
          pip install -r requirements.txt

      - name: Generate lecture codes
        run: python generate.py --type=lecture_codes

      - name: Upload lecture codes
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          include-hidden-files: true
          name: lecture_codes
          path: output/lecture_codes.json

  fetch_lecture_data:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    needs: fetch_lecture_codes

    strategy:
      matrix:
        type: [BT, CS, MS, ES, ESE5, ESE6, ESE7, X1, DS, HS, HSH1, HSH2, HSH3, HSH4, HSH5, HSH6, X3, GF, GH]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
          cache: "pip"
      - run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --upgrade get-chrome-driver
          pip install -r requirements.txt

      - name: Clean up
        run: |
          rm -rf output && mkdir output
          rm -rf docs/api/v1 && mkdir -p docs/api/v1

      - name: Download lecture codes
        uses: actions/download-artifact@v4
        with:
          name: lecture_codes
          path: output

      - name: Generate lecture data
        run: python generate.py --type=lecture_data --department=${{ matrix.type }}

      - name: Zip lecture data
        run: |
          if [ -d output/${{ matrix.type }} ]; then
            cd output && zip -r ${{ matrix.type }}.zip ${{ matrix.type }}
          fi

      - name: Upload lecture data
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: lecture_data_${{ matrix.type }}
          path: output/${{ matrix.type }}.zip

  
  commit_and_create_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs: fetch_lecture_data

    steps:
      - uses: actions/checkout@v4

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c release/auto_update_data_${{ env.CURRENT_DATETIME }}
          git push -u origin release/auto_update_data_${{ env.CURRENT_DATETIME }}

      - name: Download lecture data
        uses: actions/download-artifact@v4
        with:
          pattern: lecture_data_*
          merge-multiple: true

      - name: Unzip lecture data
        run: |
          for file in *.zip; do
            unzip -o $file -d docs/api/v1
          done
      
      - name: Create all lecture data list
        run: |
          mkdir -p docs/api/v1/all
          for file in *.zip; do
            unzip -o $file -d docs/api/v1/all
          done

      - name: Remove zip files
        run: rm -f *.zip

      - name: Add and Commit
        run: |
          git add .
          git commit -m "feat: update lecture data"
          git push origin release/auto_update_data_${{ env.CURRENT_DATETIME }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: update lecture data"
          title: "講義データの自動更新"
          body: "3ヶ月事の自動クローリング結果です。レビュー担当者は現行シラバスデータを確認し、差分を確認してください。 ※このプルリクエストは自動生成されています。"
          branch: release/auto_update_data_${{ env.CURRENT_DATETIME }}
          base: main
          assignees: "6mile0"
          reviewers: "6mile0"
