name: Fetch Latest Lecture Data and Create Pull Request

on:
  # schedule:
  #   # JST 15:40 (UTC 6:40) every 3rd day of the month (best practice: https://zenn.dev/rie_amasato/articles/f901ef9fb19415)
  #   - cron: "40 6 1 */3 *"
  push:
    branches:
      - features/modify-Actions-to-create-PR
  workflow_dispatch:

jobs:
  fetch_lecture_codes:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      lecture_codes: ${{ steps.generate_lecture_codes.outputs.lecture_codes }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
          cache: "pip"
      - run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --upgrade get-chrome-driver
          pip install -r requirements.txt

      - name: Generate lecture codes
        run: python generate.py --type=lecture_codes

      - name: Output lecture codes
        id: generate_lecture_codes
        run: echo "lecture_codes=$(cat output/lecture_codes.json | jq -c)" >> $GITHUB_ENV
        

  fetch_lecture_data:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    needs: fetch_lecture_codes

    strategy:
      matrix:
        type: [BT, CS, MS, ES, ESE5, ESE6, ESE7, X1, DS, HS, HSH1, HSH2, HSH3, HSH4, HSH5, HSH6, X3, GF, GH]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
          cache: "pip"
      - run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --upgrade get-chrome-driver
          pip install -r requirements.txt

      - name: Generate lecture codes
        run: python generate.py --type=lecture_codes

      - name: Update lecture codes
        run: echo "${{ needs.fetch_lecture_codes.outputs.lecture_codes }}" > output/lecture_codes.json

      - name: Generate lecture data for each department
        run: python generate.py --type=lecture_data --department=${{ matrix.type }}

      - name: Zip lecture data
        run: zip -r {{ matrix.type }}.zip output/${{ matrix.type }}

      - name: Upload lecture data
        uses: actions/upload-artifact@v2
        with:
          name: lecture_data_${{ matrix.type }}
          path: ${{ matrix.type }}.zip

  
  commit_and_create_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs: fetch_lecture_data

    steps:
      - uses: actions/checkout@v4

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c release/auto_update_data_${{ env.CURRENT_DATETIME }}
          git push -u origin release/auto_update_data_${{ env.CURRENT_DATETIME }}

      - name: Download lecture data
        uses: actions/download-artifact@v2
        with:
          name: lecture_data_*

      - name: Unzip lecture data
        run: |
          for file in *.zip; do
            unzip -o $file -d docs/api/v1
          done
      
      # zipを再度展開し、docs/api/v1/allにすべての講義データをまとめる
      - name: Create all lecture data list
        run: |
          mkdir -p docs/api/v1/all
          for file in *.zip; do
            unzip -o $file -d docs/api/v1/all
          done

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: release/auto_update_data_${{ env.CURRENT_DATETIME }}
          message: "feat: update lecture data"
          add: "['output/lecture_codes.json', 'docs/api/v1']"
          force: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: update lecture data"
          title: "講義データの自動更新"
          body: "3ヶ月事の自動クローリング結果です。/n レビュー担当者は現行シラバスデータを確認し、差分を確認してください。/n ※このプルリクエストは自動生成されています。"
          branch: release/auto_update_data_${{ env.CURRENT_DATETIME }}
          base: main
          labels: "auto-merge"
          assignees: "6mile0"
          reviewers: "6mile0"
