name: Fetch Latest Lecture Data and Create Pull Request

on:
  # schedule:
  #   # JST 15:40 (UTC 6:40) every 3rd day of the month (best practice: https://zenn.dev/rie_amasato/articles/f901ef9fb19415)
  #   - cron: "40 6 1 */3 *"
  push:
    branches:
      - features/modify-Actions-to-create-PR
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      TZ: 'Asia/Tokyo'
      departmentList: "BT, CS, MS, ES, ESE5, ESE6, ESE7, X1, DS, HS, HSH1, HSH2, HSH3, HSH4, HSH5, HSH6, X3, GF, GH"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
          cache: "pip"
      - run: pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --upgrade get-chrome-driver
          pip install -r requirements.txt

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c release/auto_update_data_${{ env.CURRENT_DATETIME }}
          git push -u origin release/auto_update_data_${{ env.CURRENT_DATETIME }}

      - name: Generate lecture codes
        run: python generate.py --type=lecture_codes

      - name: Generate lecture data for each department
        run: |
          for department in $(echo $departmentList | tr "," "\n")
          do
            python generate.py --type=lecture_data --department=$department
          done

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: release/auto_update_data_${{ env.CURRENT_DATETIME }}
          message: "feat: update lecture data"
          add: "['output/lecture_codes.json', 'docs/api/v1']"
          force: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: update lecture data"
          title: "講義データの自動更新"
          body: "3ヶ月事の自動クローリング結果です。/n レビュー担当者は現行シラバスデータを確認し、差分が正しいか確認してください。 /n ※このPRは自動生成されています。"
          branch: release/auto_update_data_${{ env.CURRENT_DATETIME }}
          base: main
          labels: "auto-merge"
          reviewers: "6mile0"
          assignees: "6mile0"
          draft: false
          draft-issue: false
          signoff: true
          changes: "auto"
          delete-branch: true

